### ISSUE TITLE
select_general hang on Windows and macOS, sometimes on Linux too

### ISSUE THREAD

**Issue by tesuji** [zesterer/flume#44] opened 2020-09-09 02:55 UTC
https://github.com/zesterer/flume/blob/357685aa0cd60a0db227e4fe5c325f15206ff00c/tests/basic.rs#L314
hang quite often:
* https://github.com/zesterer/flume/runs/1086120098#step:7:426
* https://github.com/zesterer/flume/runs/1086009300?check_suite_focus=true#step:7:456

It has been disabled in #43 for Windows and macOS only.

**Comment by Restioson** [comment] 2020-09-15 16:50
This hangs on Linux too apparently

**Comment by lzutao** [comment] 2020-09-16 03:11
I guess we have to disable it on Linux too or fix it.

**Comment by zesterer** [comment] 2020-09-17 07:49
This implies there is a race condition. Should anybody get the time to investigate: `Selector` is quite similar to async receivers in that they don't immediately pick up items (since multiple receivers could pick up an item at once, leading to a dropped item).

**Comment by post-rex** [comment] 2020-12-03 06:55
I'm experiencing the same issue on Windows and Linux.

**Comment by post-rex** [comment] 2020-12-03 07:25
Using `wait_timeout` or similar seems to fix the problem somewhat, the Selector still hangs up, but returns successfully after the timeout passed.

**Comment by zesterer** [comment] 2020-12-03 09:56
@post-rex Sorry about this. It's on my to-do list of things to fix, perhaps over the next week.

**Comment by post-rex** [comment] 2020-12-03 11:45
> 
> 
> @post-rex Sorry about this. It's on my to-do list of things to fix, perhaps over the next week.

Thanks that would be awesome!

**Comment by matklad** [comment] 2020-12-20 08:03
Hm, I think I am hitting this. In a program I write, `Selector::wait` reliably blocks forever and takes 3/4 messages to unblock (on linux). I'll try to publish a reproduction shortly (this is code for my yet to be published blog post, I'll re-make it using crossbeam). 

This feels like a pretty critical correctness bug to me ;-) I do not want to push for a fix here (this is open source software, it absolutely is ok to let things like this slip), but I do want to note that, imo, the graveness of this bug doesn't match the production-readiness status, signaled by the readme. (and of course there's a chance that it's my code which is broken :) ).

**Comment by zesterer** [comment] 2020-12-20 23:28
@matklad Yep, this is a persistent issue that I've been trying to make time to fix for a while now. To the best of my knowledge, it's the only actual bug in the crate (at least, the crate has now been in use by quite a few projects for several months and nothing has come up besides this). Part of the reason I've not gotten to resolving it yet is that I'm rather unhappy with the API of `Selector` overall (it doesn't map particularly well to a `select!` macro) so resolving it would likely come with an overhaul of the API. This past weekend I've been overhauling another crate I maintain, `euc`, so I think I'll try to get to fixing this issue and making other improvements to `flume` in the week after the holiday period.

**Comment by zesterer** [comment] 2021-02-07 19:57
@matklad Would you happen to still be in a position to see whether you have this issue?

**Closed** 2021-02-08 10:01 UTC

**Comment by zesterer** [comment] 2021-02-08 10:02
The test that this issue specifically mentions now passes (thanks @tesuji). On the assumption that this implies that the bug if fixed, I'm closing the issue. If this turns out to not be the case, I can re-open the issue.
