### ISSUE TITLE
The last messge won't be triggered in async code block.

### ISSUE THREAD

**Issue by SethWen** [zesterer/flume#124] opened 2023-05-20 12:26 UTC
Env for the case:
```
 windows 11
 rust 1.68.0
 tokio = "1.18.2"
 flume = "0.10.14"
```

My test case is in the following.
I should run some time-consuming code after receiving message.
But the last message won't be executed.
I have comment the stange case in the following code.
I don't know is it a bug or what to do.
```
use std::time::Duration;

use flume;

#[tokio::main]
async fn main() {
    // bounded or unbounded is the same result
    let (sender, receiver) = flume::bounded(10);

    sender.send(100);
    sender.send(200);
    // !!! the last message will never finished
    sender.send(300);

    // here I can not blocking-recv messge in current thread
    // because some other logic should be executed in the following
    let receiver = receiver.clone();
    tokio::spawn(async move {
        while let Ok(delivery) = receiver.recv() {
            println!("receive: {}", delivery);
            compute(delivery).await;
        }
    });

    // some other code here

    tokio::time::sleep(Duration::from_secs(20)).await;
}

async fn compute(x: i32) {
    println!("compute {}", x);

    // Time-consuming calculation async
    tokio::spawn(async move {
       // !!! the last message wont't executed here 

        // !!! the output here won't be triggerd for the last message
        println!("compute begin: {}", x);
        tokio::time::sleep(Duration::from_secs(3)).await;
        // !!! the output here won't be triggerd for the last message
        println!("compute end: {} ", x);
    });
}

```

**Comment by zitsen** [comment] 2023-09-05 14:45
Just found this intresting...

I've test the code and the problem reproduced. But if I wrap L7-L24 in `tokio::spawn`, it works.

Code it here:

```rust
use std::time::Duration;

use flume;

#[tokio::main]
async fn main() {
    tokio::spawn(async move {
        // bounded or unbounded is the same result
        let (sender, receiver) = flume::bounded(10);

        sender.send(100);
        sender.send(200);
        // !!! the last message will never finished
        sender.send(300);

        // here I can not blocking-recv messge in current thread
        // because some other logic should be executed in the following
        let receiver = receiver.clone();
        tokio::spawn(async move {
            while let Ok(delivery) = receiver.recv() {
                println!("receive: {}", delivery);
                compute(delivery).await;
            }
        });

        // some other code here
    })
    .await
    .unwrap();

    tokio::time::sleep(Duration::from_secs(5)).await;
}

async fn compute(x: i32) {
    println!("compute {}", x);

    // Time-consuming calculation async
    tokio::spawn(async move {
        // !!! the last message wont't executed here

        // !!! the output here won't be triggerd for the last message
        println!("compute begin: {}", x);
        tokio::time::sleep(Duration::from_secs(3)).await;
        // !!! the output here won't be triggerd for the last message
        println!("compute end: {} ", x);
    });
}
```

I guess some magic things happened in `tokio::runtime::Runtime::block_on`, not the `flume` side.

But, anyway, better not trust a `tokio::spawn`ed task will run as expected unless you `await` on it.

**Comment by zitsen** [comment] 2023-09-05 15:04
This works too. Just add `drop(sender)` before sleep.

```rust
use std::time::Duration;

use flume;

#[tokio::main]
async fn main() {
    // bounded or unbounded is the same result
    let (sender, receiver) = flume::bounded(10);

    sender.send(100);
    sender.send(200);
    // !!! the last message will never finished
    sender.send(300);

    // here I can not blocking-recv messge in current thread
    // because some other logic should be executed in the following
    let receiver = receiver.clone();
    tokio::spawn(async move {
        while let Ok(delivery) = receiver.recv() {
            println!("receive: {}", delivery);
            compute(delivery).await;
        }
    });

    // some other code here
    drop(sender);

    tokio::time::sleep(Duration::from_secs(5)).await;
}

async fn compute(x: i32) {
    println!("compute {}", x);

    // Time-consuming calculation async
    tokio::spawn(async move {
        // !!! the last message wont't executed here

        // !!! the output here won't be triggerd for the last message
        println!("compute begin: {}", x);
        tokio::time::sleep(Duration::from_secs(3)).await;
        // !!! the output here won't be triggerd for the last message
        println!("compute end: {} ", x);
    });
}
```

Try to explain this: if the sender is alive, the receiver.recv() will block the current worker thread, and the last spawned task will not be scheduled to tokio runtime unless we poll it next time. So the problem is solved:

1. Add  `tokio::task::yield_now().await;` after L21.
2. Or use `recv_async()` instead of `recv()` at L19.

I've mentioned about option 2 at China Rust Conf 2023: *Always use _async methods of flume in async block*.

**Comment by zitsen** [comment] 2023-09-05 15:06
Option 1 code here:

```rust
use std::time::Duration;

use flume;

#[tokio::main]
async fn main() {
    // bounded or unbounded is the same result
    let (sender, receiver) = flume::bounded(10);

    sender.send(100);
    sender.send(200);
    // !!! the last message will never finished
    sender.send(300);

    // here I can not blocking-recv messge in current thread
    // because some other logic should be executed in the following
    let receiver = receiver.clone();
    tokio::spawn(async move {
        while let Ok(delivery) = receiver.recv() {
            println!("receive: {}", delivery);
            compute(delivery).await;
            tokio::task::yield_now().await;
        }
    });

    // some other code here

    tokio::time::sleep(Duration::from_secs(5)).await;
}

async fn compute(x: i32) {
    println!("compute {}", x);

    // Time-consuming calculation async
    tokio::spawn(async move {
        // !!! the last message wont't executed here

        // !!! the output here won't be triggerd for the last message
        println!("compute begin: {}", x);
        tokio::time::sleep(Duration::from_secs(3)).await;
        // !!! the output here won't be triggerd for the last message
        println!("compute end: {} ", x);
    });
}
```

**Comment by zesterer** [comment] 2023-09-05 19:12
Yep, synchronous functionality (like `Receiver::recv` and `Sender::send`) should not be used in an async context. Doing so may block the async runtime. This is true of pretty much all synchronous operations, not just flume.

**Comment by zitsen** [comment] 2023-09-06 01:10
> This is true of pretty much all synchronous operations, not just flume.

+1

**Comment by zesterer** [comment] 2023-09-06 08:29
I'm going to close this because I believe this is a non-issue and entirely expected. Let me know if you think otherwise.

**Closed by zesterer** 2023-09-06 08:29 UTC

**Comment by Restioson** [comment] 2023-09-06 11:59
Agree with @zesterer on this one. Makes me wish that Rust had a lint for 'significant-sync-in-async usage', for channels, locks, TCP requests, file IO, etc...
